name: ${project.name}
main: de.jeter.chatex.ChatEX
version: ${project.version}
author: Jeter
description: Chat management plugin
softdepend: [PermissionsEx,Vault,PlaceholderAPI]

commands:
    chatex:
        description: ChatEx Plugin commands

permissions:
    chatex.allowchat:
        description: Allows chatting
        default: true
