name: ${project.name}
main: de.jeter.chatex.ChatEx
version: ${project.version}
authors: [Jeter, Wizard_x]
description: Chat management plugin
softdepend: [PermissionsEx, Vault, PlaceholderAPI]

commands:
    chatex:
        description: ChatEx Plugin commands

permissions:
    chatex.allowchat:
        description: Allows chatting
        default: true
