name: ${project.name}
main: de.thejeterlp.chatex.ChatEX
version: ${project.version}
author: TheJeterLP
description: Chat management plugin
softdepend: [PermissionsEx,Vault,PlaceholderAPI]
api-version: 1.15
permissions:
    chatex.allowchat:
        description: Allows chatting
        default: true
