name: Create DevBuild

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - master

jobs:
  create-prerelease:
    if: "!startsWith(github.event.head_commit.message, 'v')"
    name: Create Dev Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.3.0
      with:
          distribution: 'zulu'
          java-version: '8'
          java-package: jdk # optional (jdk or jre) - defaults to jdk
          cache: 'maven'
    - name: Build with Maven
      run: mvn clean install
